export ALLOW_MISSING_DEPENDENCIES=true
export USE_NINJA=true
export LLVM_ENABLE_THREADS=1

add_lunch_combo lineage_h812_usu-userdebug
add_lunch_combo lineage_h812_usu-user
add_lunch_combo lineage_h812_usu-eng
